### ISSUE TITLE
service still running when i "remove"

### ISSUE THREAD

**Issue by zuoRambo** [takama/daemon#27]
as you can see,i use subcommand "remove" to remove the daemon service,but the application didn't stopped, and there will be some trouble when type "status" to check status.
![c2977fd7-be15-43d9-a059-6daa293389c6](https://cloud.githubusercontent.com/assets/4715122/17138729/381183ce-5374-11e6-8e74-7edae71d60d3.png)

**Comment by zuoRambo** [comment]
```
10072 rworkspace/golang  » ps axu|grep 7618|grep -v grep
root             7618   0.0  0.1 573410164  10740   ??  Ss    8:53PM   0:00.27 /Users/rambone/rworkspace/golang/tp-scoring-system

```

**Comment by takama** [comment]
Hi,
Yes, it's happen if you try to remove running service (without "stop" command before).
Ok, I think, need have do "stop" command during remove the service.

**Comment by zuoRambo** [comment]
@takama thanks，i get it

**Comment by takama** [comment]
Anyway, You were right to best serve of the command "Remove". It should be correct way and should not remove running service or just stop it automatically.
