### ISSUE TITLE
daemon does not work in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by maxxant** [takama/daemon#39]
Ubuntu 16.04 has systemd and upstart together. Upstart is still used for so-called "user" init (for the desktop as I understand)

> ps aux | grep upstart
> maxxant   1861  0.0  0.0  47700  4452 ?        Ss   ноя24   0:00 /sbin/upstart --user
> maxxant   1934  0.0  0.0  34080  2020 ?        S    ноя24   0:00 upstart-udev-bridge --daemon --user
> maxxant   1996  0.0  0.0  34016   336 ?        S    ноя24   0:04 upstart-dbus-bridge --daemon --system --user --bus-name system
> maxxant   2001  0.0  0.0  42508  1708 ?        S    ноя24   0:00 upstart-file-bridge --daemon --user
> maxxant   2003  0.3  0.0  34124  1392 ?        S    ноя24  30:36 upstart-dbus-bridge --daemon --session --user --bus-name session

I guess that it all had to work before change #28 which is primarily being tested for the presence of upstart and the second systemd.

I tried to fix it in https://github.com/maxxant/daemon/commit/3030e65e06c21c4b89ba3c20178e98571e73ef31 and it works fine

What do you think about it?

**Comment by takama** [comment]
LGTM Let's contribute to this? Please do not hesitate to make pull request into develop branch.

**Comment by maxxant** [comment]
fixed via pull request #40 (now in develop branch)
