### ISSUE TITLE
Remove service

### ISSUE THREAD

**Issue by Zambiorix** [takama/daemon#43]
When a remove command is issued on a running service, should the service not be stopped first?
On OSX/darwin (and possibly other systems) this is not the case

**Comment by takama** [comment]
Yes, it will be convenient. Would you like to contribute?

**Comment by Zambiorix** [comment]
Hi,

I have not forked your repository, and currently I have no time to solve this. I thought I would just mention it to you.

Thanks

Cheers

Gerd
