### ISSUE TITLE
Problem service install in freebsd

### ISSUE THREAD

**Issue by Archie1978** [takama/daemon#47]
Hello,
  When installs the service, the program places the service in "/etc/init.d" in freebsd. But it does not exist because it is "/etc/rc.d".

For the moment I made an init.d link to rc.d but can you fix it?

After the service work.

**Comment by takama** [comment]
I don't have freebsd installed right now. Could you make PR with your fix?

**Comment by Archie1978** [comment]
Sorry, after checking I renewed the error under freebsd. I think it's a conflict with my old package "kardianos / service" that does not work under freebsd and openbsd.
I close the ticket.

**Comment by Archie1978** [comment]
I would check later for openbsd ;)
