### ISSUE TITLE
name: unrecognized service under CentOS 6.5

### ISSUE THREAD

**Issue by rafw** [takama/daemon#49]
I use simplest example in README

https://github.com/takama/daemon#examples

After running the demo, I tried to stop this service with "service name stop", but returns error: "name: unrecognized service"

**Comment by takama** [comment]
Hi,
Did you use command `service name start` before?
`service.Install()` just create init.d script, nothing more.

**Comment by rafw** [comment]
The same error info.

I compiled simplest demo, and run it. And I found the "name.conf" under /etc/init/. But service name status still not work.

**Comment by takama** [comment]
If your service has been installed in CentoOS 6, it has file `/etc/init.d/<service name>`.
Do you have that file?

**Comment by rafw** [comment]
No. Only etc/init/ has name.conf file

**Comment by takama** [comment]
It means you haven't installed service, possible cases:
1. Permission denied to service installation, you should use `sudo` command to start this example.
2. Check file creation errors during execution this example.

**Comment by rafw** [comment]
Yes, "sudo" still the same. And, the example print message if error happened, but I see no error message.

**Comment by takama** [comment]
The call of `service.Install()` should create `/etc/init.d/<service name>` file or return error message. Please look at code snippets:
```
// Standard service path for systemV daemons
func (linux *systemVRecord) servicePath() string {
	return "/etc/init.d/" + linux.name
}
```
```
// Install the service
func (linux *systemVRecord) Install(args ...string) (string, error) {

	srvPath := linux.servicePath()

	file, err := os.Create(srvPath)
	if err != nil {
		return installAction + failed, err
	}
	defer file.Close()
```

**Comment by takama** [comment]
Some questions:

- Do you have `/etc/init.d` directory and some files into?
- Did you compile the binary on linux system?
- Could you send me result of the command `strace -e trace=open <your executable file>`?
  (If you don't have `strace` install it: `yum install strace`)

**Comment by rafw** [comment]
1、YES
2、NO，on OS X with env GOOS=linux arch=amd64 go build main.go
3、`[root@xxhost ~]# strace -e trace=open ./main
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=28966, si_status=0, si_utime=0, si_stime=0} ---
Install description:                                    [  OK  ]
+++ exited with 0 +++`

**Comment by takama** [comment]
Sorry, other command `strace -e trace=stat,openat ./main` or full output of `strace ./main`

**Comment by rafw** [comment]
Output of `strace -e trace=stat,openat ./main`

stat("/run/systemd/system", 0xc420076108) = -1 ENOENT (No such file or directory)
stat("/sbin/initctl", {st_mode=S_IFREG|0755, st_size=138784, ...}) = 0
stat("/usr/lib64/qt-3.3/bin/id", 0xc4200762a8) = -1 ENOENT (No such file or directory)
stat("/usr/local/sbin/id", 0xc420076378) = -1 ENOENT (No such file or directory)
stat("/usr/local/bin/id", 0xc420076448) = -1 ENOENT (No such file or directory)
stat("/sbin/id", 0xc420076518)          = -1 ENOENT (No such file or directory)
stat("/bin/id", 0xc4200765e8)           = -1 ENOENT (No such file or directory)
stat("/usr/sbin/id", 0xc4200766b8)      = -1 ENOENT (No such file or directory)
stat("/usr/bin/id", {st_mode=S_IFREG|0755, st_size=32696, ...}) = 0
openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 3
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29481, si_status=0, si_utime=0, si_stime=0} ---
stat("/etc/init/abcdef.conf", 0xc420076858) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/init/abcdef.conf", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
stat("/usr/lib64/qt-3.3/bin/abcdef", 0xc420076928) = -1 ENOENT (No such file or directory)
stat("/usr/local/sbin/abcdef", 0xc4200769f8) = -1 ENOENT (No such file or directory)
stat("/usr/local/bin/abcdef", 0xc420076ac8) = -1 ENOENT (No such file or directory)
stat("/sbin/abcdef", 0xc420076b98)      = -1 ENOENT (No such file or directory)
stat("/bin/abcdef", 0xc420076c68)       = -1 ENOENT (No such file or directory)
stat("/usr/sbin/abcdef", 0xc420076d38)  = -1 ENOENT (No such file or directory)
stat("/usr/bin/abcdef", 0xc420076e08)   = -1 ENOENT (No such file or directory)
stat("/root/bin/abcdef", 0xc420076ed8)  = -1 ENOENT (No such file or directory)
Install description:                                    [  OK  ]
+++ exited with 0 +++

**Comment by rafw** [comment]
After moving main file to /usr/local/sbin/, output of `strace -e trace=stat,openat main`

stat("/run/systemd/system", 0xc42008a108) = -1 ENOENT (No such file or directory)
stat("/sbin/initctl", {st_mode=S_IFREG|0755, st_size=138784, ...}) = 0
stat("/usr/lib64/qt-3.3/bin/id", 0xc42008a2a8) = -1 ENOENT (No such file or directory)
stat("/usr/local/sbin/id", 0xc42008a378) = -1 ENOENT (No such file or directory)
stat("/usr/local/bin/id", 0xc42008a448) = -1 ENOENT (No such file or directory)
stat("/sbin/id", 0xc42008a518)          = -1 ENOENT (No such file or directory)
stat("/bin/id", 0xc42008a5e8)           = -1 ENOENT (No such file or directory)
stat("/usr/sbin/id", 0xc42008a6b8)      = -1 ENOENT (No such file or directory)
stat("/usr/bin/id", {st_mode=S_IFREG|0755, st_size=32696, ...}) = 0
openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 3
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29665, si_status=0, si_utime=0, si_stime=0} ---
stat("/etc/init/main.conf", 0xc42008a858) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/init/main.conf", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
stat("/usr/lib64/qt-3.3/bin/main", 0xc42008a928) = -1 ENOENT (No such file or directory)
stat("/usr/local/sbin/main", {st_mode=S_IFREG|0755, st_size=3313416, ...}) = 0
stat("/usr/local/sbin/main", {st_mode=S_IFREG|0755, st_size=3313416, ...}) = 0
Install description:                                    [  OK  ]
+++ exited with 0 +++

**Comment by takama** [comment]
Do you have upstart system installed on your VM?

**Comment by rafw** [comment]
It's a physical machine. CentOS release 6.5 (Final). Text UI.
I am not sure whether upstart installed or not. Is `initctl version` the correct way to check it?
Output of `initctl version`
`init (upstart 0.6.5)`

**Comment by takama** [comment]
In this case you should use `initctl start <job>` or `initctl stop <job>` instead of `service <name> start` or `service <name> stop`.
Another advantage is using of second example with integrated commands `install`, `start`, `stop`, `remove`. You could use  `<your executable> install`, `<your executable> start`, etc

**Comment by rafw** [comment]
`initctl start main` works. But there are many .conf files under /etc/init.d, and almost all others services (like MySQL, iptables ...) can be managed by service start/stop/restart/status $SERVICE-NAME on this centos release. I think it's better to make service command working for my service.

**Comment by takama** [comment]
I see two solutions here:
Structural: adding possibility to prioritise of systems which installed from executable command line.
Quick: fork the daemon service, disable upstart module, recompile.

Can I close the ticket?

**Comment by rafw** [comment]
OK, if I really need a library like what this repo did, I will fork a new version and try to fix it. Thank you.

**Comment by takama** [comment]
I have created the new issue  #50 with label `enhancement`
