### ISSUE TITLE
install service error "readlink /proc/self/exe: no such file or directory" under centos 7.1

### ISSUE THREAD

**Issue by koangel** [takama/daemon#64]
install error "readlink /proc/self/exe: no such file or directory" under centos 7.1

at executablePath() function ,it return error  "readlink /proc/self/exe: no such file or directory"

and exec.lookup return message exec: "myservice": executable file not found in $PATH"

how to fix it?

**Comment by derkan** [comment]
With go 1.8 some changes are breaking this. 

Finding executable of current program is tricky for different OS'es and different service managers.

I've checked other projects to learn how they are finding executable path and found [OsExt](https://github.com/kardianos/osext) package.

@takama, is it feasible to remove `ExecPath()` and its dependencies from this project and instead forward people to use `OsExt` projects' [Executable()](https://github.com/kardianos/osext/blob/master/osext.go#L20) function?

**Comment by takama** [comment]
Done. Used `os.Executable` for go1.8+

**Comment by koangel** [comment]
thanks @takama @derkan ,it's FIXED,i will be close issue.
