### ISSUE TITLE
service removing problem under OSX

### ISSUE THREAD

**Issue by acamilleri** [takama/daemon#69]
Hi, i'm working on OSX 10.13.3

Service is not unload when you remove it on OSX.
You can remove service and trying to install it, you will get: "service is already running" because function Remove() doesn't unload service before removing the plist file.

Some solution possible:
1 - Add in my code Stop() before call Remove() (very bad solution)
2- In function Remove() add this code to check if service is running and stop it before remove it:
```
if _, ok := darwin.checkRunning(); ok {
	stopAction, err := darwin.Stop()
	if err != nil {
		return stopAction, err
	}
}
```

**Comment by krysennn** [comment]
@takama up
