### ISSUE TITLE
no way to specify command line arguments

### ISSUE THREAD

**Issue by bradleypeabody** [takama/daemon#7]
There seems to be no way to specify the command line arguments that are used to invoke the service.  Although it is true that many applications can make use of a configuration file to load their settings, it is not always feasible or desirable to entirely avoid using any command line arguments when the daemon is invoked.

Have you given any thought to how this could be adjusted to accommodate that?  From what I know of systemd and SystemV-style init scripts it would be fairly trivial to include command line arguments in the script itself (I don't know about the MacOS plist stuff but I assume that has similar functionality).  If a way were provided to pass in the command line arguments to Install(), then the calling app could either take them from the actual command line that was called (minus the "install" argument) or provide defaults, etc.

What do you think about that idea?

Best, Brad

**Comment by takama** [comment]
Yes, I agree, this feature will be useful. However, there are some difficulties in its implementation. In particular, the data parameters for commands "install". The difficulty is that any parameters need to pass a quoted string - but as side effect they are not subject to validation. Either pass them as they are, but then there is confusion with the actual parameters that are passed for immediately execution. Any idea?

Regards,
Igor

**Comment by bradleypeabody** [comment]
Thanks for the reply.  I'm not sure I fully understand the issue.  But let's look at an example to help clarify:

**One Idea:**

To install, I'm thinking the user would do something like:
<pre>myservice install --option-a=1 --option-b=2</pre>

In the go program, these would arrive in os.Args as:
<pre>[]string{ "myservice", "install", "--option-a=1", "--option-b=2" }</pre>

I am thinking it would be the daemon author's responsibility to determine which arguments to pass to the install function.  Here's an example of how I am thinking that would work:
<pre>
if len(os.Args) > 1 && os.Args[1] == "install" {
daemon.InstallWithArgs(os.Args[2:]...) // passes: "--option-a=1", "--option-b=2"
}
</pre>

These would then just be appended to the command line.  In the case of systemd I'm not sure that any escaping is needed, just add to the end of the ExecStart line.  For systemv, since it is just a shell script, you probably want to use single quotes around the arguments and escape any single quote inside ('...'\''...')

**Or Using Flags:**

As another note, I would consider suggesting that people use command line switches rather than arguments.  I.e. instead of checking <code>os.Args[1]</code>, using <code>flag.Bool("install", false, "Install as a service")</code>.

This leads to another, possibly better idea on the code above.  What about this:
<pre>
installFlag := flag.Bool("install", false, "Install as service")
flag.Parse()
...
if *installFlag {
  daemon.InstallWithArgs(flag.Args()...)
}
</pre>

You would invoke it like this (the "--" <a href="https://golang.org/pkg/flag/">documented here</a> explicitly stop processing flags and puts the rest in flag.Args()):
<pre>
myservice --install -- --option-a=1 --option-b=2 some/other/thing/or/whatever.dat
</pre>

This gives you a clear separation between the install flag and what is supposed to be passed as the arguments to the daemon to put in the install file.

--

Sorry that was so long.  Tell me if you like either of those ideas.

Best, Brad

**Comment by takama** [comment]
Please imagine that someone is already using this package. And he uses the flags or arguments for their own purposes (loading of config data, anything else). Purpose: without breaking the processing of arguments for the user add a new opportunity. If we use the arguments following commands as is "install", then they can be processed earlier than will be dispatched to installWithArgs. That is, the arguments will be interpreted and performed before they needed. It is important, without breaking the code of users who are already using this package, gently add the new feature.

thanks,
Igor

**Comment by takama** [comment]
it was released
