### ISSUE TITLE
Add support for LaunchAgents on macOSX

### ISSUE THREAD

**Issue by itskingori** [takama/daemon#89]
**Summary**

I'd like to add support for LaunchAgents (user daemons in macOSX). Use case is I'd like to use this package to manage user daemons. Here's kind of the overview of the differences:

<img width="884" alt="Screenshot 2020-04-15 at 16 08 55" src="https://user-images.githubusercontent.com/703786/79340816-8cc4f880-7f33-11ea-9433-af7c2d2fde66.png">

**Details**

Currently this package supports only `LaunchDaemons` :

https://github.com/takama/daemon/blob/aa76b0035d1239b7bb3ae1bd84cd88ef2e0a1f1e/daemon.go#L9-L10

I'm wondering if you would consider adding support for `LaunchAgents`? Seems where we create the `.plist` file is the biggest difference (well, that and I guess permissions since it would run as the logged in user):

https://github.com/takama/daemon/blob/aa76b0035d1239b7bb3ae1bd84cd88ef2e0a1f1e/daemon_darwin.go#L28-L31

I'd like to take a stab at adding support for this. So consider this a scoping exercise of sorts to:

1. Gauge your interest - is this something you'd like me to contribute to your library?
2. Get feedback on approach - before I write any code, wanna know: are you're ok with the approach below?

On approach, I'm thinking of updating `darwinRecord ` to have an `userAgent bool` field ...

https://github.com/takama/daemon/blob/aa76b0035d1239b7bb3ae1bd84cd88ef2e0a1f1e/daemon_darwin.go#L17-L21

Actual implementation might be slightly different but the idea is provide a way to know what type of deamon we want and then internally change the flow based on use case e.g. use `/Library/LaunchAgents/` instead of `/Library/LaunchDaemons/` when it's a user daemon, etc.

Lemme know what you think.

**References**

* https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html
* https://apple.stackexchange.com/questions/290945/what-are-the-differences-between-launchagents-and-launchdaemons
* https://ieftimov.com/post/create-manage-macos-launchd-agents-golang/
* https://launchd.info/

**Comment by takama** [comment]
A very good proposal.

**Comment by itskingori** [comment]
Alright, thanks. Will take create a PR and we can take it from there.

**Comment by itskingori** [comment]
See PR https://github.com/takama/daemon/pull/90.

**Comment by takama** [comment]
Resolved in #90
