### ISSUE TITLE
daemon service does not work in suse11sp3

### ISSUE THREAD

**Issue by jgbooks** [takama/daemon#93]
>tag:1.0.0
>os :Linux suse11SP3X64 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux

##My execution order is as follows：
```
suse11SP3X64:~ # ./mytest remove
Removing My Echo Service:					[  OK  ]
suse11SP3X64:~ # ./mytest install
Install My Echo Service:					[  OK  ]
suse11SP3X64:~ # ./mytest start
Starting My Echo Service:					[  OK  ]
suse11SP3X64:~ # ./mytest status
Service is stopped
suse11SP3X64:~ # ./mytest stop
Stopping My Echo Service:					[FAILED] 
Error:  Service has already been stopped
suse11SP3X64:~ # ./mytest start
Starting My Echo Service:					[  OK  ]
suse11SP3X64:~ # ./mytest status
Service is stopped
suse11SP3X64:~ # ./mytest stop
Stopping My Echo Service:					[FAILED] 
Error:  Service has already been stopped
suse11SP3X64:~ # ./mytest status
Service is stopped
suse11SP3X64:~ # ./mytest status
Service is stopped
suse11SP3X64:~ # ./mytest start
Starting My Echo Service:					[FAILED] 
Error:  exit status 7
suse11SP3X64:~ # 

```

**Comment by jgbooks** [comment]
-bash: status: command not found

**Comment by JGbooks** [comment]
in this system , /etc/init.d/funtions is not exsit. so service dose not work.I solved it by adding the following code in daemon_linux_systemv.go
`
get_pid() {
    cat "$pidfile"
}

is_running() {
    [ -f "$pidfile" ] && ps $(get_pid) > /dev/null 2>&1
}

rh_status_q() {
   if [ -f /etc/rc.d/init.d/functions ]; then
        rh_status >/dev/null 2>&1
    else
        [ -f "$pidfile" ] && ps $(get_pid) > /dev/null 2>&1
    fi
}
`
`
....
    status)
		if [ -f /etc/rc.d/init.d/functions ]; then
        	rh_status
    	else
        	[ -f "$pidfile" ] && ps $(get_pid) > /dev/null 2>&1
			if [ $? == 0 ];then
				echo "$proc pid $(get_pid) is running"
			else	
				echo "$proc is stopped"
			fi 
    	fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
`
**I am a novice, please give me more advice**

**Comment by jgbooks** [comment]
[I refer to this project](https://github.com/kardianos/service/blob/master/service_sysv_linux.go) `https://github.com/kardianos/service/blob/master/service_sysv_linux.go`
